### ISSUE TITLE
Add HTTPS Support

### ISSUE THREAD

**Issue by yotammanor** [hasadna/kikar-hamedina#270]
Kikar.org is currently available only in http, this should change.

**Comment by uda** [comment]
I did my end and enabled HTTPS on the server, now you need to change http assets to https.

**Comment by yotammanor** [comment]
@uda what does it entail?

**Comment by uda** [comment]
jquery and google fonts are loaded via http, both have https support, so there is no reason to use the http url.
jQuery: https://github.com/hasadna/kikar-hamedina/search?utf8=%E2%9C%93&q=jquery-latest.js&type=
Google APIs: https://github.com/hasadna/kikar-hamedina/search?utf8=%E2%9C%93&q=googleapis&type=

The best solution would be to adopt the schemaless approach which is to use URLs with neither HTTP or HTTPS, just `//somehost/some/url`. that is if they support both, this way your app will work fine locally and on production.

This is all about CSS and JS.

There is another issue with stuff like embedded videos from Mako, we will need to check how we solve it, since it isn't under our control what the MKs share.
